version: '3'
services:
  fdp:
    build: .
    command: fdp-run 0.0.0.0 8080 --db http://db:8890/sparql
    environment: 
      - VIRTUAL_HOST=fdp.semanticscience.org,fairdatapoint.semanticscience.org
      - VIRTUAL_PORT=8080
      # - LETSENCRYPT_HOST=fdp.semanticscience.org,fairdatapoint.semanticscience.org
    expose:
      - "8080"
    # ports:
    #   - "8080:8080"
    # healthcheck:
    #     test: curl --silent --fail http://0.0.0.0:8080 || exit 1
    #     interval: 5s
    depends_on:
      - db
  db:
    image: "tenforce/virtuoso"
    # ports:
    #     - "8890:8890"
    #     - "1111:1111"
    environment:
        SPARQL_UPDATE: "true"