version: '3'
services:
  fdp:
    build: .
    command: fdp-run 0.0.0.0 80 --db http://db:8890/sparql
    # ports:
    #   - "80:80"
    environment: 
      - VIRTUAL_HOST=fdp.semanticscience.org
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
      # - LETSENCRYPT_HOST=fdp.semanticscience.org
    depends_on:
      - db
  db:
    image: "tenforce/virtuoso"
    # ports:
    #   - "8890:8890"
    #   - "1111:1111"
    environment:
      - SPARQL_UPDATE=true
    volumes:
      - /data/fdp-python/virtuoso:/data